Smart contract
kadaster-labs/sensrnet-sync pull request #29
Opened 2020-12-02 12:31 UTC by kad-floriw

Create a blockchain variable when registering sensors + owners. Initially, this variable can only be edited by its creator. The variable holds the adresses which may append to the sensor / owner stream key. This can be used in a smart-contract.
Support for approving smart-contracts (50% of admins need to approve a smart-contract for it to function).

2020-12-02 12:45 UTC, marcvanandel approved these changes, later dismissed
Ik zie geen rare dingen ... Als ik het goed begrijp, is dit alleen nog maar de connectie / integratie vanuit de `sync` naar de multichain smart contract, right?

2020-12-02 12:51 UTC, kad-floriw commented
> Ik zie geen rare dingen ... Als ik het goed begrijp, is dit alleen nog maar de connectie / integratie vanuit de `sync` naar de multichain smart contract, right?

Yes, ik heb een 2e PR klaargezet in de sensrnet-multichain repo het het smart contract :)

2020-12-02 14:21 UTC, kad-busses requested changes
Ziet er prima uit! 

Heb nog wat minisuggesties voor wijzigingen (die voor `patch-package` zijn hetzelfde als in https://github.com/kadaster-labs/sensrnet-multichain/pull/9)

2020-12-02 14:21 UTC, kad-busses commented on package.json
> +    "patch-package": "^6.2.2"
Zelfde opmerking als bij `sensrnet-multichain`, nog ff `postinstall` toevoegen en de patch zelf beetje uitbreiden 😉

2020-12-02 14:21 UTC, kad-busses commented on src/sync/multichain/multichain.controller.ts
> +  async disApproveFilter(@Body() body: ApproveBody): Promise<void> {
hoofdletter teveel: `disApproveFilter` -> `disapproveFilter` 🙂

2020-12-03 07:22 UTC, kad-busses approved these changes
Looking good!

2020-12-03 13:27 UTC, merged